name: CI
on: [push]
jobs:
  v1:
    runs-on: ubuntu-latest
    steps: 
      - run: npm install webpack webpack-cli@1
      - run: echo '.' > webpack.config.js
      - run: npx webpack
  v2:
    runs-on: ubuntu-latest
    steps: 
      - run: npm install webpack webpack-cli@2
      - run: echo '.' > webpack.config.js
      - run: npx webpack
  v3:
    runs-on: ubuntu-latest
    steps: 
      - run: npm install webpack webpack-cli@3
      - run: echo '.' > webpack.config.js
      - run: npx webpack
  v4:
    runs-on: ubuntu-latest
    steps: 
      - run: npm install webpack webpack-cli@4
      - run: echo '.' > webpack.config.js
      - run: npx webpack

  1cc1fa0:
    runs-on: ubuntu-latest
    steps: 
      - run: npm install webpack webpack/webpack-cli#1cc1fa07c59b102364f9c57d379b89e42201dab8
      - run: echo '.' > webpack.config.js
      - run: npx webpack
